import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

val nonogramEnv = providers.gradleProperty("nonogram.env").getOrElse("dev")
val isProd = nonogramEnv == "prod"
val versionBase = providers.gradleProperty("nonogram.version").getOrElse("1.1")
val versionPatch = providers.gradleProperty("nonogram.versionPatch").getOrElse("0")
val appVersion = "$versionBase.$versionPatch"

val generateBuildInfo = tasks.register("generateBuildInfo") {
    description = "generates build info"
    val outputDir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    val version = appVersion
    val prod = isProd
    inputs.property("version", version)
    inputs.property("isProd", prod)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/trainpaths/nonogram/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.trainpaths.nonogram

            // Generated by :desktopApp:generateBuildInfo - do not edit.
            object BuildInfo {
                const val VERSION = "$version"
                const val IS_PROD = $prod
            }

            """.trimIndent()
        )
    }
}

kotlin {
    jvmToolchain(21)

    jvm("desktop")

    sourceSets {
        named("desktopMain") {
            kotlin.srcDir("src/$nonogramEnv/kotlin")
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(projects.shared)

                implementation(compose.desktop.currentOs)
                implementation(libs.compose.components.resources)
                implementation(libs.koin.core)
                implementation(libs.koin.compose.viewmodel)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }
    }
}

compose.resources {
    packageOfResClass = "com.trainpaths.nonogram.desktop.resources"
    generateResClass = always
}

compose.desktop {
    application {
        mainClass = "com.trainpaths.nonogram.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Msi, TargetFormat.Dmg, TargetFormat.Deb)
            packageName = if (isProd) "nonogram" else "nonogram-dev"
            packageVersion = appVersion
            vendor = "trainpaths"
            // sqlite-jdbc needs java.sql; Firestore's grpc/netty stack reaches for Unsafe
            // kmpauth's desktop OAuth loopback listens on com.sun.net.httpserver
            // java.net.http is the update check's HttpClient - jlink drops it otherwise, and only a packaged build notices
            modules("java.sql", "jdk.unsupported", "jdk.httpserver", "java.net.http")

            linux {
                iconFile.set(project.file("src/desktopMain/composeResources/drawable/icon.png"))
                debMaintainer = "dev@noahbachmann.ch"
                appCategory = "Game"
                menuGroup = "Games"
                shortcut = true
            }
            windows {
                iconFile.set(project.file("icons/icon.ico"))
                upgradeUuid = if (isProd) {
                    "8fd365e4-c993-44a9-bdf0-d5c674d38286"
                } else {
                    "3e781c5d-c42f-4999-90e1-6a32a681804c"
                }
                menuGroup = if (isProd) "Nonogram" else "Nonogram (dev)"
                perUserInstall = true
                dirChooser = true
                shortcut = true
                menu = true
            }
            macOS { iconFile.set(project.file("icons/icon.icns")) }
        }

        // Firestore's grpc stack under ProGuard is not worth the keep rules
        buildTypes.release.proguard {
            isEnabled.set(false)
        }
    }
}
